#This layout is based upon the template 'economy.yml' 
title:
  x: 420 #650
  y: 52.5
  width: 217.5 #385
  height: 180
  font_size: 8
  align: left

title_bkgd:
  x: 420 #650
  y: 90
  width: 200 #385
  height: 25 #50
  fill_color: '#1111'
  stroke_color: '#0000'

art:
  x: 37.5
  y: 37.5
  width: 600
  height: 600

description:
  x: 420 #700
  y: 140 #165
  width: 217.5 #335
  height: 200 #260
  valign: top
  align: left
  font_size: 5
desc: # alias
  extends: description

desc_bkgd:
  x: 100
  y: 450
  width: 200 #600
  height: 200 #275
  fill_color: '#7777'
  stroke_color: '#0000'

cost:
  x: 75
  y: 75
  width: 35
  height: 25
  font_size: 8
  align: center

type:
  x: 90
  y: 955
  width: 645
  height: 50
  align: center

play:
  x: 52.5
  y: 400 #700
  width: 200 #260
  height: 200 #335
  font_size: 5
  valign: bottom
  align: left

play_bkgd:
  x: 90
  y: 400 #700
  width: 200 #260
  height: 200 #335
  fill_color: '#7777'
  stroke_color: '#0000'


recycle:
  x: 420 #775
  y: 400 #700
  width: 217.5 #260
  height: 200 #335
  font_size: 5
  valign: bottom
  align: left

lower_right:
  x: 975
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 37.5
  y: 600
  width: 225
  height: 37.5
  font_size: 5
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 600
  height: 600
